name: jobactions/nuget-prepare-publish
runs:
  using: composite
  steps:
  - uses: kagekirin/gha-utils/.github/actions/install-prerequisites@main
  - uses: kagekirin/gha-dotnet/.github/actions/nuget-add-registry@main
    with:
      name: github-nuget
      registry: https://nuget.pkg.github.com/kagekirin/unity.mathematics.nuget/index.json
      username: kagekirin
      token: ${{ github.token }}
  - uses: ./.github/jobactions/build
    with:
      framework: netstandard2.1
      configuration: Release
  - uses: ./.github/actions/nuget-pack
    with:
      framework: netstandard2.1
  - uses: ./.github/jobactions/build
    with:
      framework: net6.0
      configuration: Release
  - uses: ./.github/actions/nuget-pack
    with:
      framework: net6.0
  - uses: ./.github/jobactions/build
    with:
      framework: net7.0
      configuration: Release
  - uses: ./.github/actions/nuget-pack
    with:
      framework: net7.0
