name: fetch-source
runs:
  using: composite
  steps:
  - uses: kagekirin/gha-utils/.github/actions/git-checkout-repo@main
    with:
      repositoryUrl: https://github.com/Unity-Technologies/Unity.Mathematics.git
      repositoryPath: Unity.Mathematics-orig
      repositoryBranch: master
  - name: Copy source files
    shell: bash
    run: |
      cp Unity.Mathematics-orig/src/Unity.Mathematics/*.cs Unity.Mathematics/
      rm Unity.Mathematics/math_unity_conversion.cs
      sed -i -e "s/UnityEngine.PropertyAttribute/System.Attribute/g" Unity.Mathematics/PropertyAttributes.cs
