name: Unity.Mathematics.NuGet/build-cron

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
        framework: [netstandard2.1, net6.0, net7.0]
    steps:
    - uses: kagekirin/gha-utils/.github/actions/git-checkout-tags@main
    - uses: ./.github/actions/fetch-source
    - uses: ./.github/jobactions/build
      with:
        configuration: ${{ matrix.configuration }}
        framework: ${{ matrix.framework }}

  test-nuget:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: kagekirin/gha-utils/.github/actions/git-checkout-tags@main
    - uses: ./.github/actions/fetch-source
    - uses: ./.github/jobactions/nuget-prepare-publish
      with:
        name: github-nuget
        token: ${{ secrets.GH_NUGET_TOKEN }}

  tag:
    runs-on: ubuntu-latest
    needs: tag
    steps:
    - uses: kagekirin/gha-utils/.github/actions/git-checkout-tags@main
      with:
        ssh-key: "${{secrets.DEPLOY_KEY}}"
    - uses: ./.github/actions/fetch-source
    - id: create-tag
      uses: ./.github/jobactions/tag
      with:
        prerelease: '1'
    - uses: kagekirin/gha-utils/.github/actions/git-push-tag@main
      with:
        remote: origin
        branch: main
